const fs = require('fs');

const NEW_BU_CODES = `{
  '22nd daa': '8540',
  'business & economic developmnt': '0509',
  'ca arts council': '8260',
  'ca conservation corps': '3340',
  'ca health benefit exchange': '4800',
  'ca school finance authority': '0985',
  'ca tahoe conservancy': '3125',
  'cal fire': '3540',
  'csu, bakersfield': '6610',
  'csu, channel islands': '6610',
  'csu channel islands': '6610',
  'csu, dominguez hills': '6610',
  'csu, east bay': '6610',
  'csu, fresno': '6610',
  'csu, fullerton': '6610',
  'csu, sacramento': '6610',
  'csu, san bernardino': '6610',
  'csu, san diego': '6610',
  'csu, sonoma': '6610',
  'correctional trng rehab aut': '5225',
  'dgs - statewide procurement': '7760',
  'department of cannabis control': '1111',
  'department of conservation': '3480',
  'department of consumer affairs': '1111',
  'department of education': '6100',
  'department of fish & wildlife': '3600',
  'department of general services': '7760',
  'department of human resources': '8380',
  'department of insurance': '0845',
  'department of justice': '0820',
  'department of motor vehicles': '2740',
  'department of public health': '4265',
  'department of rehabilitation': '5160',
  'department of social services': '5180',
  'department of state hospitals': '4440',
  'department of technology': '7502',
  'department of transportation': '2660',
  'caltrans': '2660',
  'department of water resources': '3860',
  'dept of corrections & rehab': '5225',
  'dept of developmental services': '4300',
  'dept of food & agriculture': '8570',
  'department of food and agriculture': '8570',
  'dept of industrial relations': '7350',
  'dept of managed health care': '4150',
  'dept of parks & recreation': '3790',
  'dept of pesticide regulation': '3930',
  'dept of tax and fee admin': '7600',
  'dept of veterans affairs': '8955',
  'dept of the ca highway patrol': '2720',
  'california highway patrol': '2720',
  'dept. alcoholic beverage cntrl': '2100',
  'dept. toxic substances control': '3960',
  'employment development dept': '7100',
  'energy resources conservation': '3360',
  'env\\'l health hazard assessment': '3980',
  'exposition park': '3100',
  'first 5 california': '4250',
  'franchise tax board': '7730',
  'gov ofc serv and community eng': '0650',
  'gov\\'s off of lnd use & clmt in': '0650',
  'hope for children trust acct': '0950',
  'high speed rail authority': '2665',
  'institute for regenerative med': '6445',
  'judicial branch': '0250',
  'military department': '8940',
  'ofc technology and solutions i': '0531',
  'office of emergency services': '0690',
  'office of energy infrastructur': '3355',
  'office of exposition park': '3100',
  'public employees\\' retirement': '7900',
  'public employees retirement': '7900',
  'public utilities commission': '8660',
  'sf bay conservation commission': '3820',
  'school for the deaf-riverside': '6100',
  'state air resources board': '3900',
  'state board of equalization': '0860',
  'state coastal conservancy': '3760',
  'state controller': '0840',
  'state dept hlth care services': '4260',
  'state teachers\\' retirement sys': '7920',
  'state water resources control': '3940',
  'statewide stpd': '7502',
  'superior court of san bernardi': '0250',
  'uc davis medical center': '6440',
  'uc santa cruz': '6440',
  'ucla': '6440',
};`;

const routePath = 'src/app/api/caleprocure/[eventId]/route.ts';
let code = fs.readFileSync(routePath, 'utf8');

code = code.replace(/const BU_CODES: Record<string, string> = \{[\s\S]*?\};/, `const BU_CODES: Record<string, string> = ${NEW_BU_CODES}`);

fs.writeFileSync(routePath, code);
